#!/bin/sh

systemctl enable firewalld
systemctl start firewalld

firewall-cmd --add-masquerade --permanent; firewall-cmd --reload


yum -y install syslinux xinetd tftp-server vsftpd


echo -e "Configuring dhcp server: /n"
yum -y install dhcp
cat <<EOF >/etc/dhcp/dhcpd.conf
ddns-update-style none;
option space PXE;
subnet 172.25.0.0 netmask 255.255.255.0 {

class "PXE" {
	match if substring(option vendor-class-identifier, 0, 9) = "PXEClient";
		option vendor-encapsulated-options 01:04:00:00:00:00:ff;
			option boot-size 0x1;
			filename "pxelinux.0";
			option tftp-server-name "172.25.0.254";
			option vendor-class-identifier "PXEClient";
			vendor-option-space PXE;
}

	option routers 172.25.0.254;
	option subnet-mask 255.255.0.0;
	option domain-name "example.com"; 
	option domain-name-servers 172.25.0.254;
	default-lease-time 21600;
	max-lease-time 43200;
	pool {
	    allow members of "PXE";
	    default-lease-time 120;
	    max-lease-time 180;
	    range 172.25.0.200 172.25.0.250;
	}
	pool {
		range 172.25.0.20 172.25.0.199;
	}
	next-server 172.25.0.254;
}
EOF

systemctl enable dhcpd
systemctl start dhcpd

echo -e "Configuring pxe server: /n"
yum -y install syslinux xinetd tftp-server 
mkdir /var/lib/tftpboot/pxelinux.cfg
cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/ 

sed -i -e 's/.*disable.*= yes/        disable                 = no/g' /etc/xinetd.d/tftp
systemctl enable xinetd
systemctl start xinetd


mkdir /var/ftp/pub/dvd
mount /dev/cdrom /var/ftp/pub/dvd
setsebool ftpd_full_access on

cp /var/ftp/pub/dvd/images/pxeboot/vmlinuz /var/lib/tftpboot/ 
cp /var/ftp/pub/dvd/images/pxeboot/initrd.img /var/lib/tftpboot/
cp /usr/share/syslinux/menu.c32 /var/lib/tftpboot/ 

cat <<EOF >/var/lib/tftpboot/pxelinux.cfg/default
timeout 100
default menu.c32

menu title ########## PXE Boot Menu ##########
label 1
   menu label ^1) Install CentOS 7
   kernel vmlinuz
   append initrd=initrd.img method=ftp://172.25.0.254/pub/dvd devfs=nomount

label 2
   menu label ^2) Boot from local drive
   localboot
EOF

for i in http ftp dns dhcp tftp; do
    firewall-cmd --permanent --add-service $i;
done
firewall-cmd --reload

echo -e "Configuring IPA & DNS server: /n"
yum install -y bind bind-utils


yum install -y ipa-server ipa-server-dns

yum install -y rng-tools
rngd -r /dev/urandom

sed -i /.*classroom.*/d /etc/hosts
echo "172.25.0.254 classroom.example.com classroom" >> /etc/hosts

ipa-server-install \
    --domain=example.com \
    --realm=EXAMPLE.COM \
    --ds-password=password \
    --admin-password=password \
    --hostname=classroom.example.com \
    --ip-address=172.25.0.254 \
    --reverse-zone=0.25.172.in-addr.arpa. \
    --forwarder=8.8.8.8 \
    --allow-zone-overlap \
    --setup-dns \
    --unattended

for i in http https ldap ldaps kerberos kpasswd dns ntp; do
    firewall-cmd --permanent --add-service $i;
done
firewall-cmd --reload

yum install -y vsftpd
systemctl enable vsftpd
systemctl start vsftpd

firewall-cmd --add-service ftp --permanent; firewall-cmd --reload

cp /root/cacert.p12 /var/ftp/pub

echo -n 'password' | kinit admin
ipa user-add lisa --first=lisa --last=jones
echo 'password' | ipa passwd lisa
ipa user-add linda --first=linda --last=thomsen
echo 'password' | ipa passwd linda

ipa host-add server.example.com --ip-address=172.25.0.11
ipa host-add desktop.example.com --ip-address=172.25.0.10
ipa service-add nfs/server.example.com
ipa service-add cifs/server.example.com
ipa-getkeytab -s classroom.example.com -p nfs/server.example.com@EXAMPLE.COM -k /var/ftp/pub/server.keytab
ipa-getkeytab -s classroom.example.com -p cifs/server.example.com@EXAMPLE.COM -k /var/ftp/pub/server.keytab
ipa-getkeytab -s classroom.example.com -p host/server.example.com@EXAMPLE.COM -k /var/ftp/pub/server.keytab
ipa-getkeytab -s classroom.example.com -p host/desktop.example.com@EXAMPLE.COM -k /var/ftp/pub/desktop.keytab

chmod +r /var/ftp/pub/*.keytab
