#!/bin/sh

systemctl enable firewalld
systemctl start firewalld

firewall-cmd --add-masquerade --permanent; firewall-cmd --reload


yum -y install syslinux xinetd tftp-server named vsftpd


echo -e "Configuring dhcp server: /n"
yum -y install dhcp
cat <<EOF >/etc/dhcp/dhcpd.conf
ddns-update-style none;
option space PXE;
subnet 172.25.0.0 netmask 255.255.255.0 {

class "PXE" {
	match if substring(option vendor-class-identifier, 0, 9) = "PXEClient";
		option vendor-encapsulated-options 01:04:00:00:00:00:ff;
			option boot-size 0x1;
			filename "pxelinux.0";
			option tftp-server-name "172.25.0.254";
			option vendor-class-identifier "PXEClient";
			vendor-option-space PXE;
}

	option routers 172.25.0.254;
	option subnet-mask 255.255.0.0;
	option domain-name "example.com"; 
	option domain-name-servers 172.25.0.254;
	default-lease-time 21600;
	max-lease-time 43200;
	pool {
	    allow members of "PXE";
	    default-lease-time 120;
	    max-lease-time 180;
	    range 172.25.0.200 172.25.0.250;
	}
	pool {
		range 172.25.0.20 172.25.0.199;
	}
	next-server 172.25.0.254;
}
EOF

systemctl enable dhcpd
systemctl start dhcpd

echo -e "Configuring pxe server: /n"
yum -y install syslinux xinetd tftp-server 
mkdir /var/lib/tftpboot/pxelinux.cfg
cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/ 

sed -i -e 's/.*disable.*= yes/        disable                 = no/g' /etc/xinetd.d/tftp
systemctl enable xinetd
systemctl start xinetd


mkdir /var/ftp/pub/dvd
mount /dev/cdrom /var/ftp/pub/dvd
setsebool ftpd_full_access on

cp /var/ftp/pub/dvd/images/pxeboot/vmlinuz /var/lib/tftpboot/ 
cp /var/ftp/pub/dvd/images/pxeboot/initrd.img /var/lib/tftpboot/
cp /usr/share/syslinux/menu.c32 /var/lib/tftpboot/ 

cat <<EOF >/var/lib/tftpboot/pxelinux.cfg/default
timeout 100
default menu.c32

menu title ########## PXE Boot Menu ##########
label 1
   menu label ^1) Install CentOS 7
   kernel vmlinuz
   append initrd=initrd.img method=ftp://172.25.0.254/pub/dvd devfs=nomount

label 2
   menu label ^2) Boot from local drive
   localboot
EOF


sed -i '/.*classroom.*/d' /etc/hosts
echo "172.25.0.254 classroom.example.com classroom" >> /etc/hosts


for i in http ftp dns dhcp tftp; do
    firewall-cmd --permanent --add-service $i;
done
firewall-cmd --reload



systemctl enable named
systemctl start named

systemctl enable vsftpd
systemctl start vsftpd

