#!/bin/sh

cat <<EOF >/etc/yum.repos.d/installmedia-dvd.repo
[installmedia-dvd]
name = Red Hat Local DVD Repository
baseurl =ftp://172.25.0.254/pub/dvd
enabled = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
gpgcheck = 1
cost = 50
EOF


yum group install -y "Server with GUI"
systemctl set-default graphical.target
systemctl isolate graphical.target
